#!/usr/bin/env bash
#
# Call yarn shadow-cljs watch and then launch node.
#
set -euo pipefail

output_dir=.cljs
output_file=$output_dir/repl.js

shadow_pid_file=".shadow-cljs/server.pid"

function do_cleanup {
    pkill "$(cat $shadow_pid_file)"
}

trap "set +e; do_cleanup" ERR SIGTERM SIGINT EXIT

set +e
rm -v "$output_file"
set -e

shadow_cmd="clojure -A:dev -m shadow.cljs.devtools.cli watch repl $@"

$shadow_cmd &

# active loop waiting for the js file to appear
echo -n ' '
while [ ! -f "$output_file" ]; do
    for c in / - \\ \|; do
        printf '\b%s' "$c";
        sleep .1
    done
done

node --inspect $output_file
